### ISSUE TITLE
[BUG] hcp 7t

### ISSUE THREAD

**Issue by arnaudbore** [scilus/tractoflow#76]
No b0 found during Normalize_DWI process.
MRtrix dwinormalise fail :

```
Command:  dwiextract 100610__dwi_cropped.nii.gz -fslgrad 100610_dwi.bvec 100610_dwi.bval -bzero - | mrmath - mean - -axis 3 | mrstats - -mask fa_masked.nii.gz -output median

dwinormalise: [ERROR] dwiextract 100610__dwi_cropped.nii.gz -fslgrad 100610_dwi.bvec 100610_dwi.bval -bzero - | mrmath - mean - -axis 3 | mrstats - -mask fa_masked.nii.gz -output median (individual.py:66)
dwinormalise: [ERROR] Information from failed command:
dwinormalise:
              dwiextract: uncompressing image "100610__dwi_cropped.nii.gz"... [==================================================]
              dwiextract: [ERROR] No b=0 volumes present
              mrmath: [ERROR] no filename supplied to standard input (broken pipe?)
              mrmath: [ERROR] error opening image "-"
              mrstats: [ERROR] no filename supplied to standard input (broken pipe?)
              mrstats: [ERROR] error opening image "-"
```
